# Generated by Django 5.0.7 on 2024-07-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="name",
            new_name="tag",
        ),
    ]
